package com.moretolearn.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "employee") // It's validate table name in dynamodb. if not it will not create the table
public class Employee {

	@DynamoDBHashKey(attributeName = "emp_id") // It's mark the fileds as hash key in dynamodb
	@DynamoDBAutoGeneratedKey // It will make the hask key as autogenerated and it is supports only string type
	private String empId;
	
	@DynamoDBAttribute(attributeName = "emp_name")
	private String empName;
	
	@DynamoDBAttribute(attributeName = "emp_salary")
	private Double empSalary;
	
	@DynamoDBAttribute(attributeName = "emp_age")
	private Integer empAge;
}

